### ISSUE TITLE
try to create components TodoNewTask, TodoList and TodoListItem

### ISSUE THREAD

**Issue by alvarosacari** [Devpaz/todolist-vue#2]
## Description

- Podrian crear componentes para el formulario de nueva tarea y para la lista de tareas

## Screenshots

![image](https://user-images.githubusercontent.com/8761785/224224009-f6a0d6b4-6ec5-4073-9445-f0537829a8e7.png)

**Comment by Devpaz** [comment]
**Component - ToDoNewTask**
![image](https://user-images.githubusercontent.com/5315991/225771892-b8c858af-2f24-4d6a-96e2-374c1410abeb.png)

**Component - ToDoList**
![image](https://user-images.githubusercontent.com/5315991/225772111-79f6e02a-6286-4360-ae1b-631e82bf862a.png)

**Component - ToDoListItem**
![image](https://user-images.githubusercontent.com/5315991/225772198-02b89a66-1986-4a3e-9842-50f0ee402fef.png)
